### ISSUE TITLE
request to open folders with xdg-open instead of method used

### ISSUE THREAD

**Issue by CRAG666** [otsaloma/catapult#10]
When trying to open a folder with the application it will not open, checking in debug mode note that it tries to use xterm, I do not use that terminal, I only have kitty installed

**Comment by otsaloma** [comment]
What desktop environment (GNOME/KDE/...) do you use?

I had hoped that Gio, which the files plugin uses would work across different desktops, but could be that it doesn't.

**Comment by CRAG666** [comment]
Gio works fine, however I use hunter as a file manager, it works in terminal and with this it does not work. I think it would be nice to add a section in the plugin settings where an application can be selected to open folders (by default it can be xdg-open or gio)

**Comment by otsaloma** [comment]
So I'm guessing you have the `inode/directory` mimetype association set correctly, but Gio doesn't know which terminal to use. How would xdg-open help there?

I found this, maybe it helps: https://xdavidwu.link/gtk/gio-launch-set-terminal/

**Comment by CRAG666** [comment]
Well I assigned an environment variable and it worked, but it would be great if you could define your own command to open folders, also not to open another problem, why not include file search?

**Comment by otsaloma** [comment]
If I understood this problem correctly, I'm not adding preferences for cases as weird as a terminal file manager and an uncommon terminal.

Regarding file search, maybe you didn't notice, but you can configure the file/folder paths that are indexed in the preferences dialog. It defaults to `/home/user/*` just to have something in there, but you can add whatever you need there, both files and folders. You can also use recursive patterns, such as `/home/user/**/*.pdf`. If you're unsure how the patterns work, you can test them at the Python prompt

```python
>>> import glob
>>> glob.glob("/home/XXX/**/*.pdf", recurse=True)
```
