### ISSUE TITLE
Changing the fonts

### ISSUE THREAD

**Issue by emash** [otsaloma/catapult#14]
Hello everyone. I just installed Catapult on Solus, it works well, but how do i change the font from monospace to default system-wide font?

**Comment by otsaloma** [comment]
The font is currently part of the theme, so you'd need to create a minimal custom theme

https://github.com/otsaloma/catapult/blob/master/doc/themes.md

```
@import "@dark@";

.catapult-input-entry {
  font-family: "Cascadia Code", monospace;
}

.catapult-search-result-title {
  font-family: "Red Hat Text", sans-serif;
}

.catapult-search-result-description {
  font-family: "Cascadia Code", monospace;
}
```

sans-serif and monospace might give you the system defaults, not sure. You can also try ui-sans-serif and ui-monospace.

Maybe these should be configurable easier, but not really sure how well it works configuring the font alone. Testing is welcome and I'm open to suggestions.

Also, if you're wondering why it's not using the system fonts by default, my observation was that system fonts often work well at the small sizes they're primarily used, but at bigger sizes, like in catapult, fancier fonts with a bit more detail seem to work better.  And then there's people who don't use a terminal and haven't configured the system default monospace font which could then be some lousy distro or desktop default.

**Comment by emash** [comment]
Thank you for your fast reply. Everything is great now.

**Comment by otsaloma** [comment]
Nice to hear. I'll keep this issue open to track making this easier.

**Comment by emash** [comment]
Still i have this setup:
`.catapult-body {
  border-radius: 14;
  box-shadow: none;
}
.catapult-input-entry {
  font-family: "Clear Sans Bold", sans-serif, bold;
}

.catapult-search-result-title {
  font-family: "Clear Sans Bold", sans-serif;
}

.catapult-search-result-description {
  font-family: "Clear Sans Bold", sans-serif;
}`
And 'input-entry' seems to still be monospace, what I am doing wrong? Other two fonts changed well.

**Comment by otsaloma** [comment]
Oh, sorry, that was for the latest development version, I just changed the structure two weeks ago: https://github.com/otsaloma/catapult/commit/b03a524fbf97185bbc5e42a0d0f98715d9324711

You can make it like below and it should work with both the latest release and the upcoming one.

```
.catapult-input, .catapult-input-entry {
  ...
}
```

Also if you need bold, the proper CSS syntax is:

```
font-family: "Clear Sans", sans-serif;
font-weight: bold;
```

**Comment by emash** [comment]
Thanks, it's awesome with current build, I really like it
