### ISSUE TITLE
I will develop plugins

### ISSUE THREAD

**Issue by CRAG666** [otsaloma/catapult#17]
Hello, first of all I thank you again for this amazing plugin, second is that I plan to migrate some ulauncher and albert plugins to catapult. Start with the translator. But it's a bit slow, maybe it's my fault, but if you have any optimization suggestions I would really appreciate it.

````python
import json
import re
import urllib.parse
import urllib.request

from catapult.api import (Plugin, SearchResult, copy_text_to_clipboard,
                          lookup_icon)
from catapult.i18n import _

PATTERN = r"^tr\s([a-z]{2})\s([a-z]{2})\s(.*)"


class TranslatorPlugin(Plugin):
    save_history = False
    title = _("Translator")

    def __init__(self):
        super().__init__()

    def launch(self, window, id):
        copy_text_to_clipboard(id)

    def google_translate(self, text, source_language, target_language):
        base_url = "https://translate.googleapis.com/translate_a/single?client=gtx&sl={0}&tl={1}&dt=t&q={2}"
        url = base_url.format(
            source_language, target_language, urllib.parse.quote(text)
        )
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
        }
        req = urllib.request.Request(url, headers=headers)
        response = urllib.request.urlopen(req).read().decode("utf-8")
        result = json.loads(response)[0][0][0]
        return result

    def search(self, query):
        match = re.match(PATTERN, query)
        if not match:
            return

        src, dest, text = match.groups()
        result = self.google_translate(text, src, dest)

        if result:
            yield SearchResult(
                description=result,
                fuzzy=False,
                icon=lookup_icon(
                    "gnome-translate",
                    "deepin-translator",
                    "org.gnome.Translate",
                    "org.gnome.Translate",
                    "application-x-executable",
                ),
                id=result,
                offset=0,
                plugin=self,
                score=1,
                title="Traduccion",
            )
````
I also wanted to ask if it is better to use your account for the plugins, or do I use mine with a new repository?

**Comment by CRAG666** [comment]
@otsaloma Thanks

**Comment by otsaloma** [comment]
I just tried it, I think it works fast, I don't see an issue with that. Catapult doesn't really have any fancy debounce or async query updates so it could be an issue if it was _really_ slow. Otherwise some suggestions:

* Since Catapult doesn't (and will generally not) have any prefix/keyword syntax, I'd recommend using something closer to natural language like "horse to fi" or "horse from en to fi" as the pattern. Compare unit conversions in the calculator, such as "1 USD to EUR" or "1 km to mi".
* In the returned `SearchResult`, you should probably swap the description and title fields

Regarding distribution, there isn't anything yet, but the way I have though about it is that you'd put the code in your repo and add the topic "catapult-plugin". I'd then add the link to https://github.com/topics/catapult-plugin on the website and the GitHub README. Your repo should be set up so that users could just clone it directly (`cd ~/.local/share/catapult/plugins && git clone https://github.com/...` or something) without any separate installation step.

This seems to me a minimal setup that facilitates discovery, installation and updates (by manually running `git pull`). I know it's not the easiest for users, but I don't really have the motivation to set up a fancy website or automated installation routines. Having observed many other launcher projects, I'm well aware that plugins are of greatly varying quality and over time prone to cause a lot issues, so I also want to minimize my exposure to those and keep the issues between plugin authors and users.

**Comment by otsaloma** [comment]
> Your repo should be set up so that users could just clone it directly [...] without any separate installation step.

Well, that didn't work, but should be fixed now: https://github.com/otsaloma/catapult/commit/22e9956e7d8465f03723363b5a50ebb9a0917a6c

**Comment by CRAG666** [comment]
The problems become more evident when translating long texts, such as this comment. If you have any suggestions that's fine.
@otsaloma thanks

**Comment by otsaloma** [comment]
I doubt there's much to be done if it's at Google's end. You could of course use something like `requests.Session` to reuse connections but that would require users installing the additional package and perhaps sometimes recreating the session, so it's probably not worth the trouble.

For the UI, maybe we could change the search icon next to the input be a spinner when something is running a bit longer. For the plugin code that could look something like

```
with self.spinner():
    result = self.google_translate(text, src, dest)
```

If that looks useful, I could look into that.

**Comment by CRAG666** [comment]
After several iterations I managed to make it work a little faster, but maybe my hardware is biased with the 12 cores it has. now to translate you have to confirm with a space at the end of what you want to translate, this prevents requests from being sent for each key press and delegating only to the final space of the word, it also has a cache for repeated translations or backslides in the moment a translation is deleted.

````python
import asyncio
import hashlib
import re

import aiohttp
# import requests
from catapult.api import (Plugin, SearchResult, copy_text_to_clipboard,
                          lookup_icon)
from catapult.i18n import _

cache = {}

PATTERN = r"^tr\s([a-z]{2})\s([a-z]{2})\s(.*)\s"


class TranslatorPlugin(Plugin):
    save_history = False
    title = _("Translator")
    cache_key = ""

    def __init__(self):
        super().__init__()

    def launch(self, window, id):
        copy_text_to_clipboard(cache.get(self.cache_key, ""))

    async def google_translate(self, text, source_language, target_language):
        self.cache_key = hashlib.md5(
            f"{text}{source_language}{target_language}".encode()
        ).hexdigest()
        if self.cache_key in cache:
            return cache[self.cache_key]

        url = "https://translate.googleapis.com/translate_a/single"
        params = {
            "client": "gtx",
            "sl": source_language,
            "tl": target_language,
            "dt": "t",
            "q": text,
        }
        headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3"
        }
        async with aiohttp.ClientSession(headers=headers) as session:
            async with session.get(url, params=params, timeout=3) as response:
                result = (await response.json())[0][0][0]
                cache[self.cache_key] = result
        return result

    def search(self, query):
        match = re.match(PATTERN, query)
        if not match:
            return

        src, dest, text = match.groups()
        result = asyncio.run(self.google_translate(text, src, dest))
        if result:
            yield SearchResult(
                description=result,
                fuzzy=False,
                icon=lookup_icon(
                    "gnome-translate",
                    "deepin-translator",
                    "org.gnome.Translate",
                    "org.gnome.Translate",
                    "application-x-executable",
                ),
                id="0",
                offset=0,
                plugin=self,
                score=1,
                title="Traduccion",
            )
````
What you propose would also be excellent, because if there is a loading indicator it would be more convenient for the user, it also helps the plugin developer
@otsaloma thanks

**Comment by otsaloma** [comment]
I added an issue for spinner. I might want to finish the GTK 4 port first, so it might be a while before I get to it.

One detail in your code: You should relay the `cache_key` as the `id` field in the `SearchResult`, which then goes as an argument to the `launch` function. Using `self.cache_key` like in your current code could in some corner cases result in a mismatch where the activated result had a different key than what is the latest.

**Comment by CRAG666** [comment]
@otsaloma pleace chek this https://github.com/CRAG666/catapult-plugins-collection

**Comment by otsaloma** [comment]
> @otsaloma pleace chek this https://github.com/CRAG666/catapult-plugins-collection

I think it looks fine.

A small detail – `from catapult.i18n import _` and the use of `_` is probably useless. Catapult translation files will not include any plugin strings. I've thought about the translation issue and my current view is that translations for plugins are probably too much of a hassle and it'd be easier if they are just English-only.

I'll add links to https://github.com/topics/catapult-plugin sometime during the weekend so users can find these plugins.

**Comment by otsaloma** [comment]
> I'll add links to https://github.com/topics/catapult-plugin sometime during the weekend so users can find these plugins.

Done now.
