### ISSUE TITLE
Add 'build' and 'uninstall' make targets

### ISSUE THREAD

**Issue by scabala** [otsaloma/catapult#2]
Right now, it is not straightforward how to uninstall application. Having special target in Makefile called 'uninstall' would help a ton.

Another thing is current state of 'install' target: it combines building app (Python egg/wheel, translations, etc.) with installing them in proper locations. Installing in system locations requires root access and building app with root privileges is not good thing. So it would be nice to separate them.

**Comment by otsaloma** [comment]
An uninstall target is not customary and would be problematic to implement correctly. And anyway, having distros package Catapult is a better way to solve (un)installation issues than some weird Makefile stuff that very few will use.

What's your need for a separate build target? There's already `DESTDIR` in the Makefile, which e.g. distro packages should be able to use, something like

    make DESTDIR=pkg PREFIX=/usr install

**Comment by scabala** [comment]
Targeting catapult to be packaged by different distros seems good idea. Also uninstalling is not trivial as you said.
Having separate build target is more popular from my experience and is expected by different packaging systems - i.e. in RPM-based distro, there are separate steps `build` and `install`. Various programs use just `make build` and `make install` command in them. There are also predefined macros for that.

Another reason to have separate build target is that: as a user/packager, I would like to inspect what will be installed, like generated translation files, without performing actual installation.

Another reason is root privilege - roght now, to install Catapult I need to execute `gettext` command with root privileges since appropriate files are generated during `install` target. If there's some hypothetical vulnerability in `gettext` utility, it would be bad to execute it as root.

I created such new `build` target and can make a PR with it.

**Comment by otsaloma** [comment]
Yeah, go ahead, make a PR, we can take a look.
