### ISSUE TITLE
Wont scroll with arrow keys

### ISSUE THREAD

**Issue by alex3236** [otsaloma/catapult#22]
If I use Up/DownArrow key to choose results, the list doesnt scroll

**Comment by otsaloma** [comment]
Are you using 0.999? Scrolling was fixed in August: https://github.com/otsaloma/catapult/commit/76cc02b1f9d7411b5bf8c1dc658816ca8cdaacc6

**Comment by alex3236** [comment]
Sorry I forgot checking the latest build.
