### ISSUE TITLE
Slow response

### ISSUE THREAD

**Issue by alex3236** [otsaloma/catapult#23]
When you indexed large amount of files, Catapult become slow when you pressing keys.

I haven't do any debugging, but based on the appearance, it seems that the slow response is caused by rendering the icon in real time. 

Maybe add a search interval (don't search immediately on key press) and do lazy load for temporarily invisible content?

**Comment by otsaloma** [comment]
Maybe I should limit the total amount of results to something like 20 per plugin? It doesn't make sense to try to display any huge result list, no one's going to scroll through that.

Also, the files plugin in Catapult is not really designed sensibly handle huge indexes, I'd recommend indexing top-level directories like `~/*`, `~/Projects/*` etc. and continuing navigation in a file browser. Or, if you need huge indexes, someone (not me) should write a plugin that interacts with Tracker or whatever you already have running on your system.

**Comment by otsaloma** [comment]
I tried to the above with a file index of 73k files. It seemed to work fine to me. Feel free to test it, otherwise I'll assume this is fixed.

**Comment by alex3236** [comment]
I believe it's fixed now. Thanks for your kind response.
