### ISSUE TITLE
Python ModuleNotFoundError in 1.0.1 version

### ISSUE THREAD

**Issue by sandboiii** [otsaloma/catapult#26]
Hello, I've updated from 0.999 to 1.0.1 version and now there is import error when I launch catapult:
```bash
error sending Activate message to application: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
Traceback (most recent call last):
  File "/usr/bin/catapult-start", line 6, in <module>
    import catapult
ModuleNotFoundError: No module named 'catapult'
```

On previous version there was no error. My system is ArchLinux

**Comment by otsaloma** [comment]
Hi! The installation mechanism was changed with 1.0, so it's possible there's some new issue.

Can you post the content of your `/usr/bin/catapult-start`? (That file is generated during installation and should refer to the installation path.) Also, check `which -a catapult-start` to make sure you don't have conflicting installations. It should give only one path as output.

For comparison, I have installed under `/usr/local`, so my `/usr/local/bin/catapult-start` says

```
$ cat /usr/local/bin/catapult-start
#!/usr/bin/env python3

import sys
sys.path.insert(0, "/usr/local/share/catapult")

import catapult
catapult.main(sys.argv[1:])
```

And in that directory I have

```
$ tree /usr/local/share/catapult
/usr/local/share/catapult
├── catapult
│   ├── about.py
│   ├── api.py
│   ├── app.py
│   ├── conf.py
│   ├── history.py
│   ├── i18n.py
│   ├── __init__.py
│   ├── mixins.py
│   ├── plugin.py
│   ├── plugins
│   │   ├── apps.py
│   │   ├── builtins.py
│   │   ├── calculator.py
│   │   ├── clipboard.py
│   │   ├── files.py
│   │   ├── __init__.py
│   │   └── session.py
│   ├── preferences.py
│   ├── search.py
│   ├── util.py
│   └── window.py
├── catapult.css
└── themes
    ├── dark.css
    └── light.css
```

**Comment by sandboiii** [comment]
Ok, I've changed installation location to `/usr/local` and now it works
