### ISSUE TITLE
Light and dark theme differences

### ISSUE THREAD

**Issue by UffeJakobsen** [otsaloma/catapult#28]
Switching between dark and light themes within the same catapult "session" produces a different visual result than if you stop catapult and start it again.

If you select light theme and stop catapult - start it again the visual appearance it a sort of 'crippled'
if you start catapult with dark theme and switch to light theme within the same catapult "session" the light theme looks quite different from the "crippled" visual appearance described above

**Comment by otsaloma** [comment]
Thanks for noticing, I see it too now. Probably something wrong with the `@import` — the light theme is supposed to build on top of the dark. I'll look into it.
