### ISSUE TITLE
Consider using 'data_files' and 'package_data'

### ISSUE THREAD

**Issue by scabala** [otsaloma/catapult#3]
'package_data' and 'data_files' are mechanisms provided by setuptools' to deals with non-code files that should be bundled along with code. The difference is:
- 'data_files' is for files that should be installed somewhere else than package itself (outside `site-packages`, like in `/usr/share/applications` or something)
- 'package_data' is for files that should be installed *inside* package, alongside code (inside `site-packages/package_name`)

It might be useful to take a look on them since it *might* simplify Makefile. I've done some Python packaging and can help with that.

**Comment by otsaloma** [comment]
I've done some Python packaging as well and ended up with some awful things like

https://github.com/otsaloma/gaupol/blob/master/setup.py

I'm quite happy with the current Makefile + minimal setup.py. setup.py works fine for libraries, not really for apps. The only thing here that I'm uncertain of is whether this causes problems with distro packaging.

**Comment by scabala** [comment]
I do not know what are best approaches for packaging Python applications as distro packages, too. My initial idea was to be more compatible with installation method from PyPI but that makes little sense in case of Catapult (since it is more like 'system software').
