### ISSUE TITLE
Error in arch linux

### ISSUE THREAD

**Issue by CRAG666** [otsaloma/catapult#8]
this is erro
Traceback (most recent call last):
  File "/usr/local/bin/catapult", line 4, in <module>
    __import__('pkg_resources').run_script('catapult==0.3', 'catapult')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3243, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3226, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3255, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'catapult==0.3' distribution was not found and is required by the application

It would be great if a .deb or rpm package were added and even cooler if it were available for arch linux in AUR at least
For now I would like to try the application, it looks very good, but it seems not to work :(

**Comment by otsaloma** [comment]
Thanks for the reporting this. It seems the installation did not fully succeed. Did you install with the commands in the README file? Can you paste the output from those commands?

I agree about distro packages, but I prefer to leave those to distros' package repositories and maintainers. So, I expect packages will appear some day, but don't know when. If Arch has some process for requesting a package, please try that.

**Comment by CRAG666** [comment]
make build
BUILDING PYTHON PACKAGE...
./setup-partial.py build
running build
running build_py
creating build
creating build/lib
creating build/lib/catapult
copying catapult/app.py -> build/lib/catapult
copying catapult/i18n.py -> build/lib/catapult
copying catapult/about.py -> build/lib/catapult
copying catapult/window.py -> build/lib/catapult
copying catapult/mixins.py -> build/lib/catapult
copying catapult/search.py -> build/lib/catapult
copying catapult/__init__.py -> build/lib/catapult
copying catapult/util.py -> build/lib/catapult
copying catapult/plugin.py -> build/lib/catapult
copying catapult/preferences.py -> build/lib/catapult
copying catapult/history.py -> build/lib/catapult
copying catapult/conf.py -> build/lib/catapult
creating build/lib/catapult/plugins
copying catapult/plugins/builtins.py -> build/lib/catapult/plugins
copying catapult/plugins/__init__.py -> build/lib/catapult/plugins
copying catapult/plugins/apps.py -> build/lib/catapult/plugins
copying catapult/plugins/session.py -> build/lib/catapult/plugins
copying catapult/plugins/calculator.py -> build/lib/catapult/plugins
copying catapult/plugins/files.py -> build/lib/catapult/plugins
running build_scripts
creating build/scripts-3.9
copying and adjusting bin/catapult -> build/scripts-3.9
changing mode of build/scripts-3.9/catapult from 644 to 755
BUILDING TRANSLATIONS...
mkdir -p build/mo
for LANG in `cat po/LINGUAS`; do \
echo $LANG; \
msgfmt po/$LANG.po -o build/mo/$LANG.mo; \
done
fi
BUILDING DESKTOP FILE...
msgfmt --desktop -d po \
--template data/io.otsaloma.catapult.desktop.in \
-o build/io.otsaloma.catapult.desktop
BUILDING APPDATA FILE...
msgfmt --xml -d po \
--template data/io.otsaloma.catapult.appdata.xml.in \
-o build/io.otsaloma.catapult.appdata.xml
touch build/.complete

sudo make PREFIX=/usr/local install
test -f build/.complete
INSTALLING PYTHON PACKAGE...
./setup-partial.py install  --prefix=/usr/local
running install
Checking .pth file support in /usr/local/lib/python3.9/site-packages/
/usr/bin/python3 -E -c pass
TEST FAILED: /usr/local/lib/python3.9/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /usr/local/lib/python3.9/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/deprecated/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
running bdist_egg
running egg_info
creating catapult.egg-info
writing catapult.egg-info/PKG-INFO
writing dependency_links to catapult.egg-info/dependency_links.txt
writing top-level names to catapult.egg-info/top_level.txt
writing manifest file 'catapult.egg-info/SOURCES.txt'
reading manifest file 'catapult.egg-info/SOURCES.txt'
adding license file 'COPYING'
adding license file 'AUTHORS.md'
writing manifest file 'catapult.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/app.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/i18n.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/about.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/window.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/mixins.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/search.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/__init__.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/util.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/plugin.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/preferences.py -> build/bdist.linux-x86_64/egg/catapult
creating build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/builtins.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/__init__.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/apps.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/session.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/calculator.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/plugins/files.py -> build/bdist.linux-x86_64/egg/catapult/plugins
copying build/lib/catapult/history.py -> build/bdist.linux-x86_64/egg/catapult
copying build/lib/catapult/conf.py -> build/bdist.linux-x86_64/egg/catapult
byte-compiling build/bdist.linux-x86_64/egg/catapult/app.py to app.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/i18n.py to i18n.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/about.py to about.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/window.py to window.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/mixins.py to mixins.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/search.py to search.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/util.py to util.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugin.py to plugin.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/preferences.py to preferences.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/builtins.py to builtins.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/apps.py to apps.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/session.py to session.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/calculator.py to calculator.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/plugins/files.py to files.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/history.py to history.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/catapult/conf.py to conf.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.9/catapult -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/catapult to 755
copying catapult.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying catapult.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying catapult.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying catapult.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/catapult-0.3-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing catapult-0.3-py3.9.egg
Copying catapult-0.3-py3.9.egg to /usr/local/lib/python3.9/site-packages
Installing catapult script to /usr/local/bin

Installed /usr/local/lib/python3.9/site-packages/catapult-0.3-py3.9.egg
Processing dependencies for catapult==0.3
Finished processing dependencies for catapult==0.3
INSTALLING DATA FILES...
mkdir -p /usr/local/share/catapult/themes
cp -f data/catapult.css /usr/local/share/catapult
cp -f data/themes/*.css /usr/local/share/catapult/themes
INSTALLING ICONS...
mkdir -p /usr/local/share/icons/hicolor/scalable/apps
mkdir -p /usr/local/share/icons/hicolor/symbolic/apps
cp -f data/icons/io.otsaloma.catapult.svg /usr/local/share/icons/hicolor/scalable/apps
cp -f data/icons/io.otsaloma.catapult-symbolic.svg /usr/local/share/icons/hicolor/symbolic/apps
INSTALLING TRANSLATIONS...
for LANG in `cat po/LINGUAS`; do \
echo $LANG; \
mkdir -p /usr/local/share/locale/$LANG/LC_MESSAGES; \
cp -f build/mo/$LANG.mo /usr/local/share/locale/$LANG/LC_MESSAGES/catapult.mo; \
done
fi
INSTALLING DESKTOP FILE...
mkdir -p /usr/local/share/applications
cp -f build/io.otsaloma.catapult.desktop /usr/local/share/applications
INSTALLING APPDATA FILE...
mkdir -p /usr/local/share/metainfo
cp -f build/io.otsaloma.catapult.appdata.xml /usr/local/share/metainfo

this is output

**Comment by CRAG666** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/catapult", line 4, in <module>
    __import__('pkg_resources').run_script('catapult==0.3', 'catapult')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1455, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.9/site-packages/catapult-0.3-py3.9.egg/EGG-INFO/scripts/catapult", line 16, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.9/site-packages/catapult-0.3-py3.9.egg/catapult/__init__.py", line 28, in <module>
  File "/usr/lib/python3.9/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Keybinder not available

well I already solved the previous error now I get this error

**Comment by otsaloma** [comment]
The first error:

```
TEST FAILED: /usr/local/lib/python3.9/site-packages/ does NOT support .pth files
bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from. The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:
```

I'm a bit surprised to see that Arch doesn't load Python packages from `/usr/local`. Usually `/usr` is used by the package manager and `/usr/local` for what you install from source – specifically different to avoid any conflicts. If some Arch user can explain this or suggest where to install instead, I'd be interested in hearing that.

The second error:

```
ValueError: Namespace Keybinder not available
```

You need to install Keybinder, should be "libkeybinder3" on Arch.

https://archlinux.org/packages/extra/x86_64/libkeybinder3/

**Comment by CRAG666** [comment]
I already got it working, I think I'll create a pkbuild for arch linux. Thank you very much, I am a python programmer, read the code a little, I will try to add more functions, This must be the best launcher for linux. Thanks again.
