### ISSUE TITLE
Add the names of the dependencies for arch-based distributions

### ISSUE THREAD

**Issue by CRAG666** [otsaloma/catapult#9]
I will create the package for the compilation in arch linux but it is necessary to have all the names of the dependencies necessary for the installation

**Comment by otsaloma** [comment]
I think these should do:

```
python-gobject
gtk3
libkeybinder3
libqalculate
```

If you're going to publish the package, I'd recommend waiting for version 0.3.1. Plugin configuration is currently broken, but should be fixed soon.

**Comment by CRAG666** [comment]
Better wait, I'll be waiting for the update to happen, on the other hand I plan to contribute to your code and write some add-ons. I'm really excited to see that more people are betting on the native (There is already too much bloatware made with web technology)
